use std::{
    io::Write,
    path::PathBuf,
    process::Command,
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, bail, ensure};
use clap::{Parser, ValueEnum};
use sqlx::{
    Connection, PgConnection, PgPool, migrate::Migrator, postgres::PgConnectOptions,
    sqlite::SqlitePoolOptions,
};

#[derive(Parser)]
pub struct DumpSchemaArgs {
    #[arg(long, value_enum, default_value = "postgres")]
    backend: SchemaBackend,
    /// PostgreSQL administrative URL. Requires CREATEDB; never migrated itself.
    #[arg(long, env = "DATABASE_URL")]
    database_url: Option<String>,
    /// Root containing postgres/ and sqlite/ migration directories (requires source checkout).
    #[arg(long, default_value = concat!(env!("CARGO_MANIFEST_DIR"), "/../stravia-core/migrations"))]
    migrations_dir: PathBuf,
    /// Write UTF-8 SQL to this file instead of stdout, only after export and cleanup succeed.
    #[arg(long)]
    output: Option<PathBuf>,
}

#[derive(Clone, Copy, ValueEnum)]
enum SchemaBackend {
    Postgres,
    Sqlite,
}

impl SchemaBackend {
    fn name(self) -> &'static str {
        match self {
            Self::Postgres => "postgres",
            Self::Sqlite => "sqlite",
        }
    }
}

pub async fn run(args: DumpSchemaArgs) -> Result<()> {
    let backend = args.backend.name();
    let directory = args.migrations_dir.join(backend);
    // Resolve at execution time, so newly added migrations never require updating a file list
    // or rebuilding a binary that embedded an older migration directory.
    let migrator = Migrator::new(directory.as_path())
        .await
        .with_context(|| format!("cannot load migrations from {}", directory.display()))?;
    ensure!(
        migrator.iter().next().is_some(),
        "no migrations found in {}",
        directory.display()
    );
    let ddl = match args.backend {
        SchemaBackend::Sqlite => sqlite_schema(&migrator).await?,
        SchemaBackend::Postgres => {
            let database_url = args.database_url.as_deref().context(
                "PostgreSQL export requires --database-url or DATABASE_URL for a disposable development server; the role must have CREATEDB and pg_dump must be on PATH",
            )?;
            postgres_schema(&migrator, database_url).await?
        }
    };
    let output = format!(
        "-- Stravia {backend} final-state schema\n\
         -- Generated by applying all migrations to an isolated database.\n\
         -- DBA review artifact only; initialize deployments with the server migrations.\n\
         -- SQLx migration history and business data are intentionally omitted.\n\
         -- Regenerate: stravia-tools dump-schema --backend {backend}\n\n{ddl}"
    );
    if let Some(path) = args.output {
        std::fs::write(&path, output)
            .with_context(|| format!("cannot write schema to {}", path.display()))?;
    } else {
        std::io::stdout().lock().write_all(output.as_bytes())?;
    }
    Ok(())
}

async fn sqlite_schema(migrator: &Migrator) -> Result<String> {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await?;
    let result = async {
        migrator
            .run(&pool)
            .await
            .context("SQLite migrations failed in the isolated in-memory database")?;
        let definitions = sqlx::query_scalar::<_, String>(
            "SELECT sql FROM sqlite_schema
             WHERE sql IS NOT NULL
               AND substr(name, 1, 7) <> 'sqlite_'
               AND name <> '_sqlx_migrations'
               AND tbl_name <> '_sqlx_migrations'
             ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1
                                WHEN 'view' THEN 2 ELSE 3 END, name",
        )
        .fetch_all(&pool)
        .await?;
        let mut ddl = String::new();
        for definition in definitions {
            ddl.push_str(definition.trim_end().trim_end_matches(';'));
            ddl.push_str(";\n\n");
        }
        Ok(ddl)
    }
    .await;
    pool.close().await;
    result
}

async fn postgres_schema(migrator: &Migrator, database_url: &str) -> Result<String> {
    // Validate both URL consumers before creating anything. The password stays out of argv.
    let options: PgConnectOptions = database_url
        .parse()
        .context("invalid PostgreSQL connection URL")?;
    let mut dump_url = url::Url::parse(database_url)
        .context("PostgreSQL export requires a postgres:// or postgresql:// URL")?;
    ensure!(
        matches!(dump_url.scheme(), "postgres" | "postgresql"),
        "PostgreSQL export requires a postgres:// or postgresql:// URL"
    );
    ensure!(
        !dump_url
            .query_pairs()
            .any(|(key, _)| matches!(key.as_ref(), "dbname" | "database" | "service")),
        "database/service query overrides are not supported for isolated PostgreSQL export"
    );
    let version = Command::new("pg_dump")
        .arg("--version")
        .output()
        .context("pg_dump must be installed and on PATH (use the same major version as the PostgreSQL server)")?;
    ensure!(version.status.success(), "pg_dump --version failed");

    let nonce = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
    let database = format!("stravia_schema_{}_{nonce}", std::process::id());
    let mut admin = PgConnection::connect_with(&options)
        .await
        .context("cannot connect to the PostgreSQL administrative database")?;
    // The generated identifier contains only ASCII letters, digits and underscores. CREATE
    // must succeed before entering the cleanup path: a collision must never drop an existing DB.
    sqlx::raw_sql(sqlx::AssertSqlSafe(format!("CREATE DATABASE \"{database}\" WITH TEMPLATE template0 ENCODING 'UTF8'")))
        .execute(&mut admin)
        .await
        .context("cannot create isolated schema database; use a development role with CREATEDB (no existing database was migrated)")?;
    dump_url.set_path(&format!("/{database}"));

    let result =
        dump_postgres_database(migrator, options.database(&database), dump_url.as_str()).await;
    let cleanup = sqlx::raw_sql(sqlx::AssertSqlSafe(format!("DROP DATABASE \"{database}\"")))
        .execute(&mut admin)
        .await;
    if let Err(error) = cleanup {
        let original = result
            .as_ref()
            .err()
            .map(|error| format!("; export also failed: {error:#}"))
            .unwrap_or_default();
        bail!(
            "could not remove isolated database {database}; remove it manually: {error}{original}"
        );
    }
    result
}

async fn dump_postgres_database(
    migrator: &Migrator,
    options: PgConnectOptions,
    database_url: &str,
) -> Result<String> {
    let mut dump_url = url::Url::parse(database_url)?;
    let password = dump_url
        .password()
        .map(urlencoding::decode)
        .transpose()
        .context("PostgreSQL password is not valid UTF-8")?
        .map(|value| value.into_owned());
    ensure!(
        !dump_url.query_pairs().any(|(key, _)| key == "password"),
        "put the PostgreSQL password in the URL userinfo, not a query parameter"
    );
    dump_url
        .set_password(None)
        .map_err(|_| anyhow::anyhow!("cannot remove PostgreSQL password from pg_dump URL"))?;
    let pool = PgPool::connect_with(options)
        .await
        .context("cannot connect to the newly created isolated database")?;
    let migration_result = migrator.run(&pool).await;
    pool.close().await;
    migration_result.context("PostgreSQL migrations failed in the isolated database")?;

    let mut command = Command::new("pg_dump");
    command
        .args([
            "--schema-only",
            "--no-owner",
            "--no-privileges",
            "--no-tablespaces",
            "--no-security-labels",
            "--no-password",
            "--exclude-table=public._sqlx_migrations",
        ])
        .arg("--dbname")
        .arg(dump_url.as_str());
    if let Some(password) = password {
        command.env("PGPASSWORD", password);
    }
    let dump = command.output().context("could not execute pg_dump")?;
    ensure!(
        dump.status.success(),
        "pg_dump failed: {}",
        String::from_utf8_lossy(&dump.stderr)
    );
    let sql = String::from_utf8(dump.stdout).context("pg_dump returned non-UTF-8 output")?;
    // pg_dump emits a random psql guard and tool/server version comments. Exclude only
    // these wrappers, not SQL: final constraints may legitimately use ALTER TABLE ADD.
    let mut ddl = String::new();
    for line in sql.lines() {
        if line.starts_with("\\restrict ")
            || line.starts_with("\\unrestrict ")
            || line.starts_with("-- Dumped from database version ")
            || line.starts_with("-- Dumped by pg_dump version ")
        {
            continue;
        }
        ddl.push_str(line);
        ddl.push('\n');
    }
    Ok(ddl)
}
