-- Stravia sqlite final-state schema
-- Generated by applying all migrations to an isolated database.
-- DBA review artifact only; initialize deployments with the server migrations.
-- SQLx migration history and business data are intentionally omitted.
-- Regenerate: stravia-tools dump-schema --backend sqlite

CREATE TABLE admin_identity (
    singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
    username TEXT UNIQUE,
    password_hash TEXT,
    jwt_secret TEXT NOT NULL,
    credential_revision INTEGER NOT NULL DEFAULT 1 CHECK (credential_revision > 0),
    CHECK ((username IS NULL) = (password_hash IS NULL))
);

CREATE TABLE admin_sessions (
    id TEXT PRIMARY KEY,
    identity_id INTEGER NOT NULL DEFAULT 1 CHECK (identity_id = 1),
    credential_revision INTEGER NOT NULL,
    refresh_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0 CHECK (revoked IN (0, 1)),
    FOREIGN KEY (identity_id) REFERENCES admin_identity(singleton_id) ON DELETE CASCADE
);

CREATE TABLE "agent_definition_configs" (
    definition_id TEXT PRIMARY KEY,
    enabled       INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
    model_id      TEXT REFERENCES models(id) ON DELETE SET NULL,
    updated_at    INTEGER NOT NULL,
    thinking_level TEXT
        CHECK (thinking_level IN ('off', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'))
);

CREATE TABLE agent_definition_revisions (
    definition_id TEXT NOT NULL,
    slug          TEXT NOT NULL,
    version       INTEGER NOT NULL CHECK (version > 0),
    spec_hash     TEXT NOT NULL,
    spec_json     TEXT NOT NULL CHECK (json_valid(spec_json)),
    created_at    INTEGER NOT NULL,
    PRIMARY KEY (definition_id, version),
    UNIQUE (slug, version)
);

CREATE TABLE "api_key_models" (
    api_key_id TEXT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
    model_id   TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    PRIMARY KEY (api_key_id, model_id)
);

CREATE TABLE api_keys (
    id         TEXT PRIMARY KEY,
    token      TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    is_enabled INTEGER NOT NULL DEFAULT 1,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, mcp_access_enabled INTEGER NOT NULL DEFAULT 0, concurrency_limit INTEGER CHECK (concurrency_limit > 0), transparent_injection_enabled INTEGER NOT NULL DEFAULT 0, inject_media_understanding INTEGER NOT NULL DEFAULT 0, inject_web_search INTEGER NOT NULL DEFAULT 0, inject_media_generation INTEGER NOT NULL DEFAULT 0);

CREATE TABLE artifact_download_grants (
    token_hash TEXT PRIMARY KEY,
    artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
    expires_at INTEGER NOT NULL
);

CREATE TABLE artifact_upload_parts (
    upload_id   TEXT NOT NULL REFERENCES artifact_uploads(id) ON DELETE CASCADE,
    part_number INTEGER NOT NULL CHECK (part_number > 0),
    etag        TEXT NOT NULL,
    size        INTEGER NOT NULL CHECK (size >= 0),
    PRIMARY KEY (upload_id, part_number)
);

CREATE TABLE artifact_uploads (
    id            TEXT PRIMARY KEY,
    artifact_id   TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
    principal     TEXT NOT NULL,
    token_hash    TEXT NOT NULL,
    declared_size INTEGER NOT NULL CHECK (declared_size >= 0),
    received_size INTEGER NOT NULL DEFAULT 0 CHECK (received_size >= 0),
    expires_at    INTEGER NOT NULL,
    created_at    INTEGER NOT NULL
);

CREATE TABLE artifacts (
    id           TEXT PRIMARY KEY,
    principal    TEXT NOT NULL,
    mime_type    TEXT NOT NULL,
    size         INTEGER NOT NULL CHECK (size >= 0),
    backend_key  TEXT NOT NULL,
    state        TEXT NOT NULL CHECK (state IN ('staging', 'ready')),
    expires_at   INTEGER NOT NULL,
    created_at   INTEGER NOT NULL
, storage_backend TEXT NOT NULL DEFAULT 'internal', storage_endpoint TEXT, storage_bucket TEXT);

CREATE TABLE debug_trace_manifests (
    trace_id TEXT PRIMARY KEY,
    run_id TEXT REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    rejection_id TEXT REFERENCES rejected_request_observations(id) ON DELETE CASCADE,
    relative_directory TEXT NOT NULL UNIQUE,
    bytes_written INTEGER NOT NULL DEFAULT 0, event_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL, partial_reason TEXT, tombstoned INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL, completed_at INTEGER, expires_at INTEGER NOT NULL,
    CHECK ((run_id IS NOT NULL) <> (rejection_id IS NOT NULL))
);

CREATE TABLE history_markers (
    reference TEXT PRIMARY KEY,
    principal TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('platform', 'thinking')),
    activity TEXT NOT NULL,
    tool_id TEXT,
    call_payload TEXT,
    segment_payload TEXT,
    execution_state TEXT CHECK (
        execution_state IS NULL OR
        execution_state IN ('pending', 'running', 'completed', 'failed', 'interrupted')
    ),
    execution_owner TEXT,
    lease_expires_at INTEGER,
    execution_deadline INTEGER,
    published_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    CHECK (
        (kind = 'thinking' AND tool_id IS NULL AND call_payload IS NULL
         AND execution_state IS NULL AND segment_payload IS NOT NULL)
        OR
        (kind = 'platform' AND tool_id IS NOT NULL AND call_payload IS NOT NULL
         AND execution_state IS NOT NULL AND execution_deadline IS NOT NULL)
    )
);

CREATE TABLE inference_run_observations (
    id TEXT PRIMARY KEY,
    interaction_id TEXT NOT NULL REFERENCES interaction_observations(id) ON DELETE CASCADE,
    parent_run_id TEXT REFERENCES inference_run_observations(id) ON DELETE SET NULL,
    generation_node_id TEXT,
    generation_parent_id TEXT,
    ingress_protocol TEXT NOT NULL,
    route_id TEXT NOT NULL,
    model_display_name TEXT,
    status TEXT NOT NULL,
    terminal_reason TEXT,
    user_interrupted INTEGER NOT NULL DEFAULT 0,
    background_active INTEGER NOT NULL DEFAULT 0,
    debug_enabled INTEGER NOT NULL,
    client_output_committed INTEGER NOT NULL DEFAULT 0,
    started_at INTEGER NOT NULL,
    last_active_at INTEGER NOT NULL,
    finished_at INTEGER,
    last_event_sequence INTEGER NOT NULL DEFAULT 0,
    expires_at INTEGER NOT NULL
, failure_json TEXT, request_model TEXT);

CREATE TABLE interaction_observations (
    id TEXT PRIMARY KEY,
    principal TEXT NOT NULL,
    api_key_id TEXT,
    api_key_name TEXT,
    generation_root_id TEXT,
    parent_interaction_id TEXT REFERENCES interaction_observations(id) ON DELETE SET NULL,
    root_id TEXT NOT NULL,
    root_run_id TEXT NOT NULL,
    first_route_id TEXT NOT NULL,
    first_model_display_name TEXT,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    last_active_at INTEGER NOT NULL,
    visible_tail TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER, output_tokens INTEGER, cache_read_tokens INTEGER,
    cache_write_tokens INTEGER, reasoning_tokens INTEGER,
    observation_gap INTEGER NOT NULL DEFAULT 0,
    last_event_sequence INTEGER NOT NULL DEFAULT 0,
    expires_at INTEGER NOT NULL
, input_preview TEXT);

CREATE TABLE media_derivatives (
    principal              TEXT NOT NULL,
    source_artifact_id     TEXT PRIMARY KEY REFERENCES artifacts(id) ON DELETE CASCADE,
    derivative_artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
    created_at             INTEGER NOT NULL
);

CREATE TABLE "model_backends" (
    id                     TEXT PRIMARY KEY,
    model_id               TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    provider_id            TEXT NOT NULL REFERENCES providers(id),
    model                  TEXT CHECK (model IS NULL OR length(trim(model)) > 0),
    priority               INTEGER NOT NULL DEFAULT 0,
    created_at             TEXT NOT NULL DEFAULT (datetime('now')),
    thinking_level_map     TEXT NOT NULL DEFAULT '[{"level":"off","control":{"type":"hidden"},"source":"generated"},{"level":"minimal","control":{"type":"hidden"},"source":"generated"},{"level":"low","control":{"type":"hidden"},"source":"generated"},{"level":"medium","control":{"type":"hidden"},"source":"generated"},{"level":"high","control":{"type":"hidden"},"source":"generated"},{"level":"xhigh","control":{"type":"hidden"},"source":"generated"},{"level":"max","control":{"type":"hidden"},"source":"generated"}]'
        CHECK (json_valid(thinking_level_map)),
    first_token_timeout_ms INTEGER NOT NULL DEFAULT 60000,
    target_retry_budget    INTEGER NOT NULL DEFAULT 5,
    target_cooldown_ms     INTEGER NOT NULL DEFAULT 120000,
    enabled                INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
);

CREATE TABLE model_turn_observations (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    interaction_id TEXT NOT NULL REFERENCES interaction_observations(id) ON DELETE CASCADE,
    route_id TEXT NOT NULL,
    model_display_name TEXT,
    api_key_id TEXT,
    api_key_name TEXT,
    status TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    finished_at INTEGER,
    input_tokens INTEGER, output_tokens INTEGER, cache_read_tokens INTEGER,
    cache_write_tokens INTEGER, reasoning_tokens INTEGER,
    last_event_sequence INTEGER NOT NULL
);

CREATE TABLE models (
    id           TEXT PRIMARY KEY,
    model_id     TEXT NOT NULL,
    balance      TEXT NOT NULL DEFAULT 'traffic_equalization',
    is_enabled   INTEGER NOT NULL DEFAULT 1,
    priority     INTEGER DEFAULT 0,
    created_at   TEXT NOT NULL DEFAULT (datetime('now')),
    display_name TEXT
, default_thinking_level TEXT);

CREATE TABLE native_compaction_sources (
    record_id TEXT NOT NULL REFERENCES native_compactions(id) ON DELETE CASCADE,
    source_id TEXT NOT NULL REFERENCES native_compactions(id) ON DELETE RESTRICT,
    PRIMARY KEY (record_id, source_id),
    CHECK (record_id <> source_id)
);

CREATE TABLE native_compaction_states (
    record_id TEXT NOT NULL REFERENCES native_compactions(id) ON DELETE CASCADE,
    principal TEXT NOT NULL,
    native_identity TEXT,
    fingerprint TEXT NOT NULL,
    state_payload TEXT NOT NULL CHECK (json_valid(state_payload)),
    PRIMARY KEY (record_id, fingerprint)
);

CREATE TABLE native_compactions (
    id TEXT PRIMARY KEY,
    principal TEXT NOT NULL,
    source_generation_id TEXT REFERENCES turn_chain_nodes(id) ON DELETE RESTRICT,
    operation_id TEXT NOT NULL,
    payload TEXT NOT NULL CHECK (json_valid(payload)),
    created_at INTEGER NOT NULL,
    delivered_at INTEGER,
    referenced_at INTEGER,
    expires_at INTEGER NOT NULL
);

CREATE TABLE observation_events (
    sequence INTEGER PRIMARY KEY,
    occurred_at INTEGER NOT NULL,
    interaction_id TEXT REFERENCES interaction_observations(id) ON DELETE CASCADE,
    run_id TEXT REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    rejection_id TEXT REFERENCES rejected_request_observations(id) ON DELETE CASCADE,
    kind TEXT NOT NULL, payload TEXT NOT NULL, expires_at INTEGER NOT NULL
);

CREATE TABLE observation_pending_tools (
    principal TEXT NOT NULL,
    tool_id TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    interaction_id TEXT NOT NULL REFERENCES interaction_observations(id) ON DELETE CASCADE,
    expires_at INTEGER NOT NULL,
    PRIMARY KEY (principal, tool_id, run_id)
);

CREATE TABLE observation_sequence (
    singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
    next_sequence INTEGER NOT NULL
);

CREATE TABLE observation_tail_sources (
    run_id TEXT PRIMARY KEY REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    interaction_id TEXT NOT NULL REFERENCES interaction_observations(id) ON DELETE CASCADE,
    principal TEXT NOT NULL,
    last_unit_hash TEXT NOT NULL,
    generation_node_id TEXT,
    expires_at INTEGER NOT NULL
);

CREATE TABLE provider_allowance_samples (
    id              TEXT PRIMARY KEY,
    provider_id     TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    allowance_key   TEXT NOT NULL,
    sampled_at      INTEGER NOT NULL,
    used_value      REAL,
    remaining_value REAL,
    limit_value     REAL,
    used_percent    REAL,
    amount_unit     TEXT,
    currency        TEXT,
    reset_at        INTEGER
);

CREATE TABLE provider_model_cost_rules (
    provider_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    rule_index INTEGER NOT NULL CHECK (rule_index >= 0),
    rule_kind TEXT NOT NULL CHECK (rule_kind IN ('context_over_200k', 'tier')),
    threshold_tokens INTEGER NOT NULL CHECK (threshold_tokens >= 0),
    cost_input TEXT,
    cost_output TEXT,
    cost_reasoning TEXT,
    cost_cache_read TEXT,
    cost_cache_write TEXT,
    cost_input_audio TEXT,
    cost_output_audio TEXT,
    PRIMARY KEY (provider_id, model_id, rule_index),
    FOREIGN KEY (provider_id, model_id)
        REFERENCES provider_models(provider_id, model_id)
        ON DELETE CASCADE
);

CREATE TABLE provider_models (
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('discovered', 'manual')),
    metadata_source_provider_id TEXT,
    presence TEXT NOT NULL CHECK (presence IN ('present', 'missing')),
    lifecycle_status TEXT CHECK (lifecycle_status IN ('alpha', 'beta', 'deprecated')),
    selection_policy TEXT NOT NULL DEFAULT 'auto'
        CHECK (selection_policy IN ('auto', 'force_enabled', 'force_disabled')),
    name TEXT,
    family TEXT,
    attachment INTEGER CHECK (attachment IS NULL OR attachment IN (0, 1)),
    reasoning INTEGER CHECK (reasoning IS NULL OR reasoning IN (0, 1)),
    tool_call INTEGER CHECK (tool_call IS NULL OR tool_call IN (0, 1)),
    open_weights INTEGER CHECK (open_weights IS NULL OR open_weights IN (0, 1)),
    structured_output INTEGER CHECK (structured_output IS NULL OR structured_output IN (0, 1)),
    temperature INTEGER CHECK (temperature IS NULL OR temperature IN (0, 1)),
    limit_context INTEGER CHECK (limit_context IS NULL OR limit_context >= 0),
    limit_input INTEGER CHECK (limit_input IS NULL OR limit_input >= 0),
    limit_output INTEGER CHECK (limit_output IS NULL OR limit_output >= 0),
    cost_input TEXT,
    cost_output TEXT,
    cost_reasoning TEXT,
    cost_cache_read TEXT,
    cost_cache_write TEXT,
    cost_input_audio TEXT,
    cost_output_audio TEXT,
    metadata_json TEXT NOT NULL
        CHECK (json_valid(metadata_json) AND json_type(metadata_json) = 'object'),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')), snapshot_state TEXT NOT NULL
    DEFAULT '{"type":"edited","source":null}'
    CHECK (COALESCE(CASE WHEN json_valid(snapshot_state) THEN
        json_type(snapshot_state) = 'object'
        AND CASE json_extract(snapshot_state, '$.type')
            WHEN 'unregistered' THEN json_type(snapshot_state, '$.source') IS NULL
            WHEN 'imported' THEN json_type(snapshot_state, '$.source') = 'object'
                AND CASE json_extract(snapshot_state, '$.source.type')
                    WHEN 'provider_catalog' THEN json_type(snapshot_state, '$.source.provider_id') = 'text'
                    WHEN 'canonical' THEN json_type(snapshot_state, '$.source.model_id') = 'text'
                    WHEN 'discovery' THEN 1 ELSE 0 END
            WHEN 'edited' THEN json_type(snapshot_state, '$.source') = 'null'
                OR (json_type(snapshot_state, '$.source') = 'object'
                    AND CASE json_extract(snapshot_state, '$.source.type')
                        WHEN 'provider_catalog' THEN json_type(snapshot_state, '$.source.provider_id') = 'text'
                        WHEN 'canonical' THEN json_type(snapshot_state, '$.source.model_id') = 'text'
                        WHEN 'discovery' THEN 1 ELSE 0 END)
            ELSE 0 END
        ELSE 0 END, 0)),
    PRIMARY KEY (provider_id, model_id)
);

CREATE TABLE provider_oauth_credentials (
    provider_id     TEXT PRIMARY KEY REFERENCES providers(id) ON DELETE CASCADE,
    connection_id   TEXT NOT NULL,
    driver_key      TEXT NOT NULL DEFAULT '',
    scheme          TEXT NOT NULL DEFAULT '',
    access_token    TEXT NOT NULL DEFAULT '',
    refresh_token   TEXT,
    expires_at      TEXT,
    resource_url    TEXT,
    subject_id      TEXT,
    scopes          TEXT NOT NULL DEFAULT '[]',
    meta            TEXT NOT NULL DEFAULT '{}',
    status          TEXT NOT NULL DEFAULT 'connected',
    status_version  INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    last_refresh_at TEXT,
    created_at      TEXT DEFAULT (datetime('now')),
    updated_at      TEXT DEFAULT (datetime('now'))
);

CREATE TABLE providers (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    vendor            TEXT,
    protocol          TEXT NOT NULL,
    base_url          TEXT NOT NULL,
    preset_key        TEXT,
    channel           TEXT,
    models_source     TEXT,
    static_models     TEXT,
    api_key           TEXT NOT NULL,
    auth_mode         TEXT NOT NULL DEFAULT 'apikey' CHECK (auth_mode IN ('apikey', 'oauth')),
    access_token      TEXT,
    refresh_token     TEXT,
    expires_at        TEXT,
    use_proxy         INTEGER NOT NULL DEFAULT 0,
    last_test_success INTEGER,
    last_test_at      TEXT,
    is_enabled        INTEGER NOT NULL DEFAULT 1,
    priority          INTEGER DEFAULT 0,
    created_at        TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at        TEXT NOT NULL DEFAULT (datetime('now')),
    adapter_credentials TEXT NOT NULL DEFAULT '{}',
    vendor_options    TEXT NOT NULL DEFAULT '{}',
    credential_status TEXT NOT NULL DEFAULT 'ok' CHECK (credential_status IN ('ok', 'invalid')),
    credential_invalid_at TEXT,
    revision          INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE rejected_request_observations (
    id TEXT PRIMARY KEY, occurred_at INTEGER NOT NULL, method TEXT NOT NULL, path TEXT NOT NULL,
    ingress_protocol TEXT NOT NULL, stage TEXT NOT NULL, code TEXT NOT NULL, status_code INTEGER NOT NULL,
    debug_enabled INTEGER NOT NULL, debug_status TEXT NOT NULL, last_event_sequence INTEGER NOT NULL,
    expires_at INTEGER NOT NULL
, failure_json TEXT, request_model TEXT, api_key_id TEXT, api_key_name TEXT, started_at INTEGER, duration_ms INTEGER);

CREATE TABLE reversible_redaction_mappings (
    reference TEXT PRIMARY KEY NOT NULL,
    principal TEXT NOT NULL,
    secret TEXT NOT NULL,
    published_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL
);

CREATE TABLE settings (
    name       TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE target_attempt_observations (
    id TEXT PRIMARY KEY,
    model_turn_id TEXT NOT NULL REFERENCES model_turn_observations(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL REFERENCES inference_run_observations(id) ON DELETE CASCADE,
    interaction_id TEXT NOT NULL REFERENCES interaction_observations(id) ON DELETE CASCADE,
    target_id TEXT NOT NULL, provider_id TEXT NOT NULL, provider_name TEXT NOT NULL,
    upstream_model TEXT NOT NULL, protocol TEXT NOT NULL,
    status TEXT NOT NULL, status_code INTEGER, error_code TEXT,
    started_at INTEGER NOT NULL, finished_at INTEGER, duration_ms INTEGER, first_token_ms INTEGER,
    input_tokens INTEGER, output_tokens INTEGER, cache_read_tokens INTEGER,
    cache_write_tokens INTEGER, reasoning_tokens INTEGER,
    usage_recorded INTEGER NOT NULL DEFAULT 0,
    last_event_sequence INTEGER NOT NULL
);

CREATE TABLE turn_chain_content_refs (
    node_id TEXT NOT NULL,
    principal TEXT NOT NULL,
    path TEXT NOT NULL,
    content_key TEXT NOT NULL,
    PRIMARY KEY (node_id, path),
    FOREIGN KEY (node_id, principal) REFERENCES turn_chain_nodes(id, principal) ON DELETE CASCADE,
    FOREIGN KEY (principal, content_key) REFERENCES turn_chain_contents(principal, content_key)
);

CREATE TABLE turn_chain_contents (
    principal TEXT NOT NULL,
    content_key TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (principal, content_key)
);

CREATE TABLE "turn_chain_nodes" (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('response', 'agent', 'web_search')),
    parent_id TEXT,
    principal TEXT NOT NULL,
    payload_version INTEGER NOT NULL CHECK (payload_version > 0),
    payload TEXT NOT NULL CHECK (json_valid(payload)),
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    prefix_namespace TEXT,
    prefix_fingerprint TEXT,
    prefix_item_count INTEGER,
    prefix_completed_at INTEGER,
    storage_format INTEGER NOT NULL DEFAULT 0 CHECK (storage_format IN (0, 1)),
    UNIQUE (id, principal),
    UNIQUE (id, principal, kind),
    FOREIGN KEY (parent_id, principal, kind)
        REFERENCES "turn_chain_nodes"(id, principal, kind) ON DELETE RESTRICT
);

CREATE TABLE vendor_data_recovery (
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    data_kind TEXT NOT NULL CHECK (data_kind IN ('options', 'credentials', 'models')),
    PRIMARY KEY (provider_id, data_kind)
);

CREATE TABLE vendor_plugins (
    vendor_id TEXT PRIMARY KEY,
    version TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('builtin', 'local')),
    descriptor TEXT NOT NULL,
    digest TEXT NOT NULL,
    revision BIGINT NOT NULL CHECK (revision > 0),
    data_epoch BIGINT NOT NULL CHECK (data_epoch >= 0),
    installed_at BIGINT NOT NULL
);

CREATE TABLE vendor_private_state (
    provider_id TEXT PRIMARY KEY REFERENCES providers(id) ON DELETE CASCADE,
    vendor_id TEXT NOT NULL,
    format_version TEXT NOT NULL,
    payload BLOB NOT NULL CHECK (length(payload) <= 262144),
    updated_at BIGINT NOT NULL
);

CREATE TABLE web_providers (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    kind              TEXT NOT NULL CHECK (kind IN ('local', 'exa', 'zhipu')),
    api_key           TEXT,
    use_proxy         INTEGER NOT NULL DEFAULT 0 CHECK (use_proxy IN (0, 1)),
    local_engines     TEXT,
    last_test_success INTEGER,
    last_test_at      TEXT,
    created_at        TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at        TEXT NOT NULL DEFAULT (datetime('now')),
    CHECK (
        (
            kind = 'local'
            AND api_key IS NULL
            AND local_engines IS NOT NULL
            AND json_valid(local_engines)
        )
        OR (
            kind IN ('exa', 'zhipu')
            AND api_key IS NOT NULL
            AND length(trim(api_key)) > 0
            AND local_engines IS NULL
        )
    )
);

CREATE INDEX debug_manifests_expiry_idx ON debug_trace_manifests(tombstoned, expires_at);

CREATE INDEX idx_admin_sessions_expiry ON admin_sessions(expires_at);

CREATE INDEX idx_agent_definition_revisions_slug
    ON agent_definition_revisions(slug, version);

CREATE INDEX idx_api_key_models_model_id ON api_key_models(model_id);

CREATE INDEX idx_api_keys_token ON api_keys(token);

CREATE INDEX idx_artifact_download_grants_hold ON artifact_download_grants(artifact_id, expires_at);

CREATE INDEX idx_artifact_uploads_expiry ON artifact_uploads(expires_at);

CREATE INDEX idx_artifacts_expiry ON artifacts(expires_at);

CREATE INDEX idx_history_markers_execution
ON history_markers(execution_state, lease_expires_at, execution_deadline);

CREATE INDEX idx_history_markers_expiry
ON history_markers(expires_at);

CREATE INDEX idx_history_markers_principal_reference
ON history_markers(principal, reference);

CREATE INDEX idx_media_derivatives_derivative ON media_derivatives(derivative_artifact_id);

CREATE INDEX idx_model_backends_model_id ON model_backends(model_id);

CREATE UNIQUE INDEX idx_models_route_id ON models(model_id);

CREATE INDEX idx_native_compaction_source ON native_compaction_sources(source_id);

CREATE INDEX idx_native_compaction_state_fingerprint ON native_compaction_states(principal, fingerprint);

CREATE INDEX idx_native_compaction_state_identity ON native_compaction_states(principal, native_identity);

CREATE INDEX idx_native_compactions_expiry ON native_compactions(expires_at);

CREATE UNIQUE INDEX idx_oauth_creds_connection_id ON provider_oauth_credentials(connection_id);

CREATE INDEX idx_oauth_creds_expires ON provider_oauth_credentials(expires_at);

CREATE INDEX idx_oauth_creds_status ON provider_oauth_credentials(status);

CREATE INDEX idx_observation_events_client_tool_call
    ON observation_events(run_id, json_extract(payload, '$.tool_id'), sequence DESC)
    WHERE kind IN ('client_tool_handoff', 'client_tool_result');

CREATE INDEX idx_observation_events_context
ON observation_events (interaction_id, sequence)
WHERE kind IN ('compaction_operation', 'native_compaction_associated', 'retained_tail_associated');

CREATE INDEX idx_provider_allowance_samples_item_time
    ON provider_allowance_samples(provider_id, allowance_key, sampled_at);

CREATE INDEX idx_provider_allowance_samples_sampled_at
    ON provider_allowance_samples(sampled_at);

CREATE UNIQUE INDEX idx_provider_model_cost_rules_threshold
    ON provider_model_cost_rules(provider_id, model_id, rule_kind, threshold_tokens);

CREATE INDEX idx_provider_models_provider_name
    ON provider_models(provider_id, name);

CREATE INDEX idx_provider_models_provider_state
    ON provider_models(provider_id, presence, lifecycle_status, selection_policy);

CREATE INDEX idx_reversible_redaction_mappings_expiry
ON reversible_redaction_mappings(expires_at);

CREATE INDEX idx_reversible_redaction_mappings_principal_expiry
ON reversible_redaction_mappings(principal, expires_at);

CREATE INDEX idx_turn_chain_content_refs_content ON turn_chain_content_refs(principal, content_key);

CREATE INDEX idx_turn_chain_expiry ON turn_chain_nodes(expires_at);

CREATE UNIQUE INDEX idx_turn_chain_node_principal ON turn_chain_nodes(id, principal);

CREATE INDEX idx_turn_chain_parent ON turn_chain_nodes(parent_id);

CREATE INDEX idx_turn_chain_principal_kind ON turn_chain_nodes(principal, kind);

CREATE INDEX idx_turn_chain_reusable_prefix ON turn_chain_nodes (
    principal, kind, prefix_namespace, prefix_fingerprint, prefix_item_count DESC,
    prefix_completed_at DESC, expires_at, id DESC
) WHERE prefix_namespace IS NOT NULL;

CREATE INDEX idx_vendor_private_state_vendor ON vendor_private_state(vendor_id);

CREATE UNIQUE INDEX idx_web_providers_local_singleton
ON web_providers(kind)
WHERE kind = 'local';

CREATE INDEX inference_runs_failed_window_idx
    ON inference_run_observations(started_at DESC, id) WHERE status = 'failed';

CREATE INDEX inference_runs_generation_idx ON inference_run_observations(generation_node_id, generation_parent_id);

CREATE INDEX inference_runs_interaction_idx ON inference_run_observations(interaction_id, started_at, id);

CREATE INDEX inference_runs_status_idx ON inference_run_observations(status, last_active_at);

CREATE INDEX interaction_observations_expiry_idx ON interaction_observations(expires_at);

CREATE INDEX interaction_observations_filter_idx ON interaction_observations(status, api_key_name, last_active_at DESC);

CREATE INDEX interaction_observations_generation_idx ON interaction_observations(generation_root_id, last_active_at);

CREATE INDEX interaction_observations_window_idx ON interaction_observations(root_id, last_active_at DESC, id);

CREATE INDEX model_turns_analytics_idx ON model_turn_observations(started_at, route_id, api_key_id, status);

CREATE INDEX model_turns_interaction_idx ON model_turn_observations(interaction_id, started_at, id);

CREATE INDEX observation_events_expiry_idx ON observation_events(expires_at, sequence);

CREATE INDEX observation_events_interaction_idx ON observation_events(interaction_id, sequence);

CREATE INDEX observation_events_rejection_idx ON observation_events(rejection_id, sequence);

CREATE INDEX observation_events_run_idx ON observation_events(run_id, sequence);

CREATE INDEX observation_pending_tools_expiry_idx
    ON observation_pending_tools(expires_at);

CREATE INDEX observation_pending_tools_lookup_idx
    ON observation_pending_tools(principal, tool_id);

CREATE INDEX observation_tail_sources_expiry_idx
    ON observation_tail_sources(expires_at);

CREATE INDEX observation_tail_sources_hash_idx
    ON observation_tail_sources(principal, last_unit_hash);

CREATE INDEX rejected_requests_expiry_idx ON rejected_request_observations(expires_at);

CREATE INDEX rejected_requests_started_idx
    ON rejected_request_observations(started_at DESC, id);

CREATE INDEX rejected_requests_window_idx ON rejected_request_observations(occurred_at DESC, id);

CREATE INDEX target_attempts_analytics_idx ON target_attempt_observations(started_at, provider_id, upstream_model, target_id, status);

CREATE INDEX target_attempts_turn_idx ON target_attempt_observations(model_turn_id, started_at, id);

CREATE TRIGGER api_keys_boolean_insert BEFORE INSERT ON api_keys
WHEN (typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)) OR (typeof(NEW.mcp_access_enabled) <> 'integer' OR NEW.mcp_access_enabled NOT IN (0, 1)) OR (typeof(NEW.transparent_injection_enabled) <> 'integer' OR NEW.transparent_injection_enabled NOT IN (0, 1)) OR (typeof(NEW.inject_media_understanding) <> 'integer' OR NEW.inject_media_understanding NOT IN (0, 1)) OR (typeof(NEW.inject_web_search) <> 'integer' OR NEW.inject_web_search NOT IN (0, 1)) OR (typeof(NEW.inject_media_generation) <> 'integer' OR NEW.inject_media_generation NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER api_keys_boolean_update BEFORE UPDATE ON api_keys
WHEN (typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)) OR (typeof(NEW.mcp_access_enabled) <> 'integer' OR NEW.mcp_access_enabled NOT IN (0, 1)) OR (typeof(NEW.transparent_injection_enabled) <> 'integer' OR NEW.transparent_injection_enabled NOT IN (0, 1)) OR (typeof(NEW.inject_media_understanding) <> 'integer' OR NEW.inject_media_understanding NOT IN (0, 1)) OR (typeof(NEW.inject_web_search) <> 'integer' OR NEW.inject_web_search NOT IN (0, 1)) OR (typeof(NEW.inject_media_generation) <> 'integer' OR NEW.inject_media_generation NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER debug_trace_manifests_boolean_insert BEFORE INSERT ON debug_trace_manifests
WHEN (typeof(NEW.tombstoned) <> 'integer' OR NEW.tombstoned NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER debug_trace_manifests_boolean_update BEFORE UPDATE ON debug_trace_manifests
WHEN (typeof(NEW.tombstoned) <> 'integer' OR NEW.tombstoned NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER inference_run_observations_boolean_insert BEFORE INSERT ON inference_run_observations
WHEN (typeof(NEW.user_interrupted) <> 'integer' OR NEW.user_interrupted NOT IN (0, 1)) OR (typeof(NEW.debug_enabled) <> 'integer' OR NEW.debug_enabled NOT IN (0, 1)) OR (typeof(NEW.client_output_committed) <> 'integer' OR NEW.client_output_committed NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER inference_run_observations_boolean_update BEFORE UPDATE ON inference_run_observations
WHEN (typeof(NEW.user_interrupted) <> 'integer' OR NEW.user_interrupted NOT IN (0, 1)) OR (typeof(NEW.debug_enabled) <> 'integer' OR NEW.debug_enabled NOT IN (0, 1)) OR (typeof(NEW.client_output_committed) <> 'integer' OR NEW.client_output_committed NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER inference_runs_contract_insert BEFORE INSERT ON inference_run_observations
WHEN typeof(NEW.background_active) <> 'integer' OR NEW.background_active < 0
BEGIN SELECT RAISE(ABORT, 'invalid background activity count'); END;

CREATE TRIGGER inference_runs_contract_update BEFORE UPDATE ON inference_run_observations
WHEN typeof(NEW.background_active) <> 'integer' OR NEW.background_active < 0
BEGIN SELECT RAISE(ABORT, 'invalid background activity count'); END;

CREATE TRIGGER interaction_observations_boolean_insert BEFORE INSERT ON interaction_observations
WHEN (typeof(NEW.observation_gap) <> 'integer' OR NEW.observation_gap NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER interaction_observations_boolean_update BEFORE UPDATE ON interaction_observations
WHEN (typeof(NEW.observation_gap) <> 'integer' OR NEW.observation_gap NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER model_backends_contract_insert BEFORE INSERT ON model_backends
WHEN NEW.priority IS NULL OR typeof(NEW.priority) <> 'integer' OR NEW.priority < -2147483648 OR NEW.priority > 2147483647
    OR typeof(NEW.target_retry_budget) <> 'integer' OR NEW.target_retry_budget < 0 OR NEW.target_retry_budget > 2147483647
    OR typeof(NEW.first_token_timeout_ms) <> 'integer' OR NEW.first_token_timeout_ms < 0
    OR typeof(NEW.target_cooldown_ms) <> 'integer' OR NEW.target_cooldown_ms < 0
    OR typeof(NEW.enabled) <> 'integer' OR NEW.enabled NOT IN (0, 1)
    OR CASE WHEN json_valid(NEW.thinking_level_map) THEN json_type(NEW.thinking_level_map) <> 'array' ELSE 1 END
BEGIN SELECT RAISE(ABORT, 'invalid Target configuration'); END;

CREATE TRIGGER model_backends_contract_update BEFORE UPDATE ON model_backends
WHEN NEW.priority IS NULL OR typeof(NEW.priority) <> 'integer' OR NEW.priority < -2147483648 OR NEW.priority > 2147483647
    OR typeof(NEW.target_retry_budget) <> 'integer' OR NEW.target_retry_budget < 0 OR NEW.target_retry_budget > 2147483647
    OR typeof(NEW.first_token_timeout_ms) <> 'integer' OR NEW.first_token_timeout_ms < 0
    OR typeof(NEW.target_cooldown_ms) <> 'integer' OR NEW.target_cooldown_ms < 0
    OR typeof(NEW.enabled) <> 'integer' OR NEW.enabled NOT IN (0, 1)
    OR CASE WHEN json_valid(NEW.thinking_level_map) THEN json_type(NEW.thinking_level_map) <> 'array' ELSE 1 END
BEGIN SELECT RAISE(ABORT, 'invalid Target configuration'); END;

CREATE TRIGGER models_contract_insert BEFORE INSERT ON models
WHEN NEW.balance NOT IN ('traffic_equalization', 'latency_preference')
    OR (NEW.default_thinking_level IS NOT NULL AND NEW.default_thinking_level NOT IN ('off', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'))
    OR typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)
BEGIN SELECT RAISE(ABORT, 'invalid Route configuration'); END;

CREATE TRIGGER models_contract_update BEFORE UPDATE ON models
WHEN NEW.balance NOT IN ('traffic_equalization', 'latency_preference')
    OR (NEW.default_thinking_level IS NOT NULL AND NEW.default_thinking_level NOT IN ('off', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'))
    OR typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)
BEGIN SELECT RAISE(ABORT, 'invalid Route configuration'); END;

CREATE TRIGGER providers_boolean_insert BEFORE INSERT ON providers
WHEN (NEW.last_test_success IS NOT NULL AND (typeof(NEW.last_test_success) <> 'integer' OR NEW.last_test_success NOT IN (0, 1)))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER providers_boolean_update BEFORE UPDATE ON providers
WHEN (NEW.last_test_success IS NOT NULL AND (typeof(NEW.last_test_success) <> 'integer' OR NEW.last_test_success NOT IN (0, 1)))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER providers_contract_insert BEFORE INSERT ON providers
WHEN CASE WHEN json_valid(NEW.adapter_credentials) THEN json_type(NEW.adapter_credentials) <> 'object' ELSE 1 END
    OR CASE WHEN json_valid(NEW.vendor_options) THEN json_type(NEW.vendor_options) <> 'object' ELSE 1 END
    OR typeof(NEW.use_proxy) <> 'integer' OR NEW.use_proxy NOT IN (0, 1)
    OR typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)
BEGIN SELECT RAISE(ABORT, 'invalid Provider configuration'); END;

CREATE TRIGGER providers_contract_update BEFORE UPDATE ON providers
WHEN CASE WHEN json_valid(NEW.adapter_credentials) THEN json_type(NEW.adapter_credentials) <> 'object' ELSE 1 END
    OR CASE WHEN json_valid(NEW.vendor_options) THEN json_type(NEW.vendor_options) <> 'object' ELSE 1 END
    OR typeof(NEW.use_proxy) <> 'integer' OR NEW.use_proxy NOT IN (0, 1)
    OR typeof(NEW.is_enabled) <> 'integer' OR NEW.is_enabled NOT IN (0, 1)
BEGIN SELECT RAISE(ABORT, 'invalid Provider configuration'); END;

CREATE TRIGGER rejected_request_observations_boolean_insert BEFORE INSERT ON rejected_request_observations
WHEN (typeof(NEW.debug_enabled) <> 'integer' OR NEW.debug_enabled NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER rejected_request_observations_boolean_update BEFORE UPDATE ON rejected_request_observations
WHEN (typeof(NEW.debug_enabled) <> 'integer' OR NEW.debug_enabled NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER target_attempt_observations_boolean_insert BEFORE INSERT ON target_attempt_observations
WHEN (typeof(NEW.usage_recorded) <> 'integer' OR NEW.usage_recorded NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER target_attempt_observations_boolean_update BEFORE UPDATE ON target_attempt_observations
WHEN (typeof(NEW.usage_recorded) <> 'integer' OR NEW.usage_recorded NOT IN (0, 1))
BEGIN SELECT RAISE(ABORT, 'invalid boolean value'); END;

CREATE TRIGGER web_providers_boolean_insert BEFORE INSERT ON web_providers
WHEN (typeof(NEW.use_proxy) <> 'integer' OR NEW.use_proxy NOT IN (0, 1)) OR (NEW.last_test_success IS NOT NULL AND (typeof(NEW.last_test_success) <> 'integer' OR NEW.last_test_success NOT IN (0, 1)))
    OR (NEW.kind = 'local' AND CASE WHEN json_valid(NEW.local_engines) THEN json_type(NEW.local_engines) <> 'object' ELSE 1 END)
BEGIN SELECT RAISE(ABORT, 'invalid boolean or local engine configuration'); END;

CREATE TRIGGER web_providers_boolean_update BEFORE UPDATE ON web_providers
WHEN (typeof(NEW.use_proxy) <> 'integer' OR NEW.use_proxy NOT IN (0, 1)) OR (NEW.last_test_success IS NOT NULL AND (typeof(NEW.last_test_success) <> 'integer' OR NEW.last_test_success NOT IN (0, 1)))
    OR (NEW.kind = 'local' AND CASE WHEN json_valid(NEW.local_engines) THEN json_type(NEW.local_engines) <> 'object' ELSE 1 END)
BEGIN SELECT RAISE(ABORT, 'invalid boolean or local engine configuration'); END;

