-- Stravia postgres final-state schema
-- Generated by applying all migrations to an isolated database.
-- DBA review artifact only; initialize deployments with the server migrations.
-- SQLx migration history and business data are intentionally omitted.
-- Regenerate: stravia-tools dump-schema --backend postgres

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: admin_identity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_identity (
    singleton_id smallint NOT NULL,
    username text,
    password_hash text,
    jwt_secret text NOT NULL,
    credential_revision bigint DEFAULT 1 NOT NULL,
    CONSTRAINT admin_identity_check CHECK (((username IS NULL) = (password_hash IS NULL))),
    CONSTRAINT admin_identity_credential_revision_check CHECK ((credential_revision > 0)),
    CONSTRAINT admin_identity_singleton_id_check CHECK ((singleton_id = 1))
);


--
-- Name: admin_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_sessions (
    id text NOT NULL,
    identity_id smallint DEFAULT 1 NOT NULL,
    credential_revision bigint NOT NULL,
    refresh_hash text NOT NULL,
    expires_at bigint NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    CONSTRAINT admin_sessions_identity_id_check CHECK ((identity_id = 1))
);


--
-- Name: agent_definition_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_definition_configs (
    definition_id text NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    model_id text,
    updated_at bigint NOT NULL,
    thinking_level text,
    CONSTRAINT agent_definition_configs_thinking_level_check CHECK ((thinking_level = ANY (ARRAY['off'::text, 'minimal'::text, 'low'::text, 'medium'::text, 'high'::text, 'xhigh'::text, 'max'::text])))
);


--
-- Name: agent_definition_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_definition_revisions (
    definition_id text NOT NULL,
    slug text NOT NULL,
    version bigint NOT NULL,
    spec_hash text NOT NULL,
    spec_json text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT agent_definition_revisions_version_check CHECK ((version > 0))
);


--
-- Name: api_key_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_key_models (
    api_key_id text NOT NULL,
    model_id text NOT NULL
);


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id text NOT NULL,
    token text NOT NULL,
    name text NOT NULL,
    is_enabled boolean DEFAULT true,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    mcp_access_enabled boolean DEFAULT false CONSTRAINT api_keys_web_access_enabled_not_null NOT NULL,
    concurrency_limit integer,
    transparent_injection_enabled boolean DEFAULT false NOT NULL,
    inject_media_understanding boolean DEFAULT false NOT NULL,
    inject_web_search boolean DEFAULT false NOT NULL,
    CONSTRAINT api_keys_concurrency_limit_check CHECK ((concurrency_limit > 0))
);


--
-- Name: artifact_download_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifact_download_grants (
    token_hash text NOT NULL,
    artifact_id text NOT NULL,
    expires_at bigint NOT NULL
);


--
-- Name: artifact_upload_parts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifact_upload_parts (
    upload_id text NOT NULL,
    part_number bigint NOT NULL,
    etag text NOT NULL,
    size bigint NOT NULL,
    CONSTRAINT artifact_upload_parts_part_number_check CHECK ((part_number > 0)),
    CONSTRAINT artifact_upload_parts_size_check CHECK ((size >= 0))
);


--
-- Name: artifact_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifact_uploads (
    id text NOT NULL,
    artifact_id text NOT NULL,
    principal text NOT NULL,
    token_hash text NOT NULL,
    declared_size bigint NOT NULL,
    received_size bigint DEFAULT 0 NOT NULL,
    expires_at bigint NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT artifact_uploads_declared_size_check CHECK ((declared_size >= 0)),
    CONSTRAINT artifact_uploads_received_size_check CHECK ((received_size >= 0))
);


--
-- Name: artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifacts (
    id text NOT NULL,
    principal text NOT NULL,
    mime_type text NOT NULL,
    size bigint NOT NULL,
    backend_key text NOT NULL,
    state text NOT NULL,
    expires_at bigint NOT NULL,
    created_at bigint NOT NULL,
    storage_backend text DEFAULT 'internal'::text NOT NULL,
    storage_endpoint text,
    storage_bucket text,
    CONSTRAINT artifacts_size_check CHECK ((size >= 0)),
    CONSTRAINT artifacts_state_check CHECK ((state = ANY (ARRAY['staging'::text, 'ready'::text])))
);


--
-- Name: debug_trace_manifests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.debug_trace_manifests (
    trace_id text NOT NULL,
    run_id text,
    rejection_id text,
    relative_directory text NOT NULL,
    bytes_written bigint DEFAULT 0 NOT NULL,
    event_count bigint DEFAULT 0 NOT NULL,
    status text NOT NULL,
    partial_reason text,
    tombstoned boolean DEFAULT false NOT NULL,
    created_at bigint NOT NULL,
    completed_at bigint,
    expires_at bigint NOT NULL,
    CONSTRAINT debug_trace_manifests_check CHECK (((run_id IS NOT NULL) <> (rejection_id IS NOT NULL)))
);


--
-- Name: history_markers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.history_markers (
    reference text NOT NULL,
    principal text NOT NULL,
    kind text NOT NULL,
    activity text NOT NULL,
    tool_id text,
    call_payload text,
    segment_payload text,
    execution_state text,
    execution_owner text,
    lease_expires_at bigint,
    execution_deadline bigint,
    published_at bigint,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    CONSTRAINT history_markers_check CHECK ((((kind = 'thinking'::text) AND (tool_id IS NULL) AND (call_payload IS NULL) AND (execution_state IS NULL) AND (segment_payload IS NOT NULL)) OR ((kind = 'platform'::text) AND (tool_id IS NOT NULL) AND (call_payload IS NOT NULL) AND (execution_state IS NOT NULL) AND (execution_deadline IS NOT NULL)))),
    CONSTRAINT history_markers_execution_state_check CHECK (((execution_state IS NULL) OR (execution_state = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'interrupted'::text])))),
    CONSTRAINT history_markers_kind_check CHECK ((kind = ANY (ARRAY['platform'::text, 'thinking'::text])))
);


--
-- Name: inference_run_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inference_run_observations (
    id text NOT NULL,
    interaction_id text NOT NULL,
    parent_run_id text,
    generation_node_id text,
    generation_parent_id text,
    ingress_protocol text NOT NULL,
    route_id text NOT NULL,
    model_display_name text,
    status text NOT NULL,
    terminal_reason text,
    user_interrupted boolean DEFAULT false NOT NULL,
    background_active bigint DEFAULT 0 NOT NULL,
    debug_enabled boolean NOT NULL,
    client_output_committed boolean DEFAULT false NOT NULL,
    started_at bigint NOT NULL,
    last_active_at bigint NOT NULL,
    finished_at bigint,
    last_event_sequence bigint DEFAULT 0 NOT NULL,
    expires_at bigint NOT NULL
);


--
-- Name: interaction_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interaction_observations (
    id text NOT NULL,
    principal text NOT NULL,
    api_key_id text,
    api_key_name text,
    generation_root_id text,
    parent_interaction_id text,
    root_id text NOT NULL,
    root_run_id text NOT NULL,
    first_route_id text NOT NULL,
    first_model_display_name text,
    status text NOT NULL,
    started_at bigint NOT NULL,
    last_active_at bigint NOT NULL,
    visible_tail text DEFAULT ''::text NOT NULL,
    input_tokens bigint,
    output_tokens bigint,
    cache_read_tokens bigint,
    cache_write_tokens bigint,
    reasoning_tokens bigint,
    observation_gap boolean DEFAULT false NOT NULL,
    last_event_sequence bigint DEFAULT 0 NOT NULL,
    expires_at bigint NOT NULL,
    input_preview text
);


--
-- Name: media_derivatives; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_derivatives (
    principal text NOT NULL,
    source_artifact_id text NOT NULL,
    derivative_artifact_id text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT media_derivatives_check CHECK ((source_artifact_id <> derivative_artifact_id))
);


--
-- Name: model_backends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_backends (
    id text NOT NULL,
    model_id text NOT NULL,
    provider_id text NOT NULL,
    model text NOT NULL,
    priority integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    thinking_level_map jsonb DEFAULT '[{"level": "off", "source": "generated", "control": {"type": "hidden"}}, {"level": "minimal", "source": "generated", "control": {"type": "hidden"}}, {"level": "low", "source": "generated", "control": {"type": "hidden"}}, {"level": "medium", "source": "generated", "control": {"type": "hidden"}}, {"level": "high", "source": "generated", "control": {"type": "hidden"}}, {"level": "xhigh", "source": "generated", "control": {"type": "hidden"}}, {"level": "max", "source": "generated", "control": {"type": "hidden"}}]'::jsonb NOT NULL,
    first_token_timeout_ms bigint DEFAULT 60000 NOT NULL,
    target_retry_budget integer DEFAULT 5 NOT NULL,
    target_cooldown_ms bigint DEFAULT 120000 NOT NULL,
    enabled boolean DEFAULT true NOT NULL
);


--
-- Name: model_turn_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_turn_observations (
    id text NOT NULL,
    run_id text NOT NULL,
    interaction_id text NOT NULL,
    route_id text NOT NULL,
    model_display_name text,
    api_key_id text,
    api_key_name text,
    status text NOT NULL,
    started_at bigint NOT NULL,
    finished_at bigint,
    input_tokens bigint,
    output_tokens bigint,
    cache_read_tokens bigint,
    cache_write_tokens bigint,
    reasoning_tokens bigint,
    last_event_sequence bigint NOT NULL
);


--
-- Name: models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.models (
    id text NOT NULL,
    model_id text CONSTRAINT models_name_not_null NOT NULL,
    balance text DEFAULT 'traffic_equalization'::text,
    is_enabled boolean DEFAULT true,
    priority integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    display_name text
);


--
-- Name: native_compaction_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.native_compaction_sources (
    record_id text NOT NULL,
    source_id text NOT NULL,
    CONSTRAINT native_compaction_sources_check CHECK ((record_id <> source_id))
);


--
-- Name: native_compaction_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.native_compaction_states (
    record_id text NOT NULL,
    principal text NOT NULL,
    native_identity text,
    fingerprint text NOT NULL,
    state_payload text NOT NULL
);


--
-- Name: native_compactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.native_compactions (
    id text NOT NULL,
    principal text NOT NULL,
    source_generation_id text,
    operation_id text NOT NULL,
    payload text NOT NULL,
    created_at bigint NOT NULL,
    delivered_at bigint,
    referenced_at bigint,
    expires_at bigint NOT NULL
);


--
-- Name: observation_event_sequence; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.observation_event_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: observation_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.observation_events (
    sequence bigint DEFAULT nextval('public.observation_event_sequence'::regclass) NOT NULL,
    occurred_at bigint NOT NULL,
    interaction_id text,
    run_id text,
    rejection_id text,
    kind text NOT NULL,
    payload jsonb NOT NULL,
    expires_at bigint NOT NULL
);


--
-- Name: provider_allowance_samples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_allowance_samples (
    id text NOT NULL,
    provider_id text NOT NULL,
    allowance_key text NOT NULL,
    sampled_at bigint NOT NULL,
    used_value double precision,
    remaining_value double precision,
    limit_value double precision,
    used_percent double precision,
    amount_unit text,
    currency text,
    reset_at bigint
);


--
-- Name: provider_model_cost_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_model_cost_rules (
    provider_id text NOT NULL,
    model_id text NOT NULL,
    rule_index integer NOT NULL,
    rule_kind text NOT NULL,
    threshold_tokens bigint NOT NULL,
    cost_input numeric,
    cost_output numeric,
    cost_reasoning numeric,
    cost_cache_read numeric,
    cost_cache_write numeric,
    cost_input_audio numeric,
    cost_output_audio numeric,
    CONSTRAINT provider_model_cost_rules_rule_index_check CHECK ((rule_index >= 0)),
    CONSTRAINT provider_model_cost_rules_rule_kind_check CHECK ((rule_kind = ANY (ARRAY['context_over_200k'::text, 'tier'::text]))),
    CONSTRAINT provider_model_cost_rules_threshold_tokens_check CHECK ((threshold_tokens >= 0))
);


--
-- Name: provider_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_models (
    provider_id text NOT NULL,
    model_id text NOT NULL,
    source_kind text NOT NULL,
    metadata_source_provider_id text,
    presence text NOT NULL,
    lifecycle_status text,
    selection_policy text DEFAULT 'auto'::text NOT NULL,
    name text,
    family text,
    attachment boolean,
    reasoning boolean,
    tool_call boolean,
    open_weights boolean,
    structured_output boolean,
    temperature boolean,
    limit_context bigint,
    limit_input bigint,
    limit_output bigint,
    cost_input numeric,
    cost_output numeric,
    cost_reasoning numeric,
    cost_cache_read numeric,
    cost_cache_write numeric,
    cost_input_audio numeric,
    cost_output_audio numeric,
    metadata_json jsonb NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT provider_models_lifecycle_status_check CHECK ((lifecycle_status = ANY (ARRAY['alpha'::text, 'beta'::text, 'deprecated'::text]))),
    CONSTRAINT provider_models_limit_context_check CHECK (((limit_context IS NULL) OR (limit_context >= 0))),
    CONSTRAINT provider_models_limit_input_check CHECK (((limit_input IS NULL) OR (limit_input >= 0))),
    CONSTRAINT provider_models_limit_output_check CHECK (((limit_output IS NULL) OR (limit_output >= 0))),
    CONSTRAINT provider_models_metadata_json_check CHECK ((jsonb_typeof(metadata_json) = 'object'::text)),
    CONSTRAINT provider_models_presence_check CHECK ((presence = ANY (ARRAY['present'::text, 'missing'::text]))),
    CONSTRAINT provider_models_revision_check CHECK ((revision > 0)),
    CONSTRAINT provider_models_selection_policy_check CHECK ((selection_policy = ANY (ARRAY['auto'::text, 'force_enabled'::text, 'force_disabled'::text]))),
    CONSTRAINT provider_models_source_kind_check CHECK ((source_kind = ANY (ARRAY['discovered'::text, 'manual'::text])))
);


--
-- Name: provider_oauth_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_oauth_credentials (
    provider_id text NOT NULL,
    driver_key text DEFAULT ''::text NOT NULL,
    scheme text DEFAULT ''::text NOT NULL,
    access_token text DEFAULT ''::text NOT NULL,
    refresh_token text,
    expires_at timestamp with time zone,
    resource_url text,
    subject_id text,
    scopes text DEFAULT '[]'::text NOT NULL,
    meta text DEFAULT '{}'::text NOT NULL,
    status text DEFAULT 'connected'::text NOT NULL,
    status_version integer DEFAULT 0 NOT NULL,
    last_error text,
    last_refresh_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    connection_id text NOT NULL
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id text NOT NULL,
    name text NOT NULL,
    vendor text,
    protocol text NOT NULL,
    base_url text NOT NULL,
    preset_key text,
    channel text,
    models_source text,
    static_models text,
    api_key text NOT NULL,
    auth_mode text DEFAULT 'apikey'::text NOT NULL,
    access_token text,
    refresh_token text,
    expires_at timestamp with time zone,
    use_proxy boolean DEFAULT false NOT NULL,
    last_test_success boolean,
    last_test_at timestamp with time zone,
    is_enabled boolean DEFAULT true,
    priority integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    adapter_credentials text DEFAULT '{}'::text NOT NULL,
    CONSTRAINT providers_auth_mode_check CHECK ((auth_mode = ANY (ARRAY['apikey'::text, 'oauth'::text])))
);


--
-- Name: rejected_request_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rejected_request_observations (
    id text NOT NULL,
    occurred_at bigint NOT NULL,
    method text NOT NULL,
    path text NOT NULL,
    ingress_protocol text NOT NULL,
    stage text NOT NULL,
    code text NOT NULL,
    status_code bigint NOT NULL,
    debug_enabled boolean NOT NULL,
    debug_status text NOT NULL,
    last_event_sequence bigint NOT NULL,
    expires_at bigint NOT NULL
);


--
-- Name: reversible_redaction_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reversible_redaction_mappings (
    reference text NOT NULL,
    principal text NOT NULL,
    secret text NOT NULL,
    published_at bigint,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    expires_at bigint NOT NULL
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    name text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: target_attempt_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.target_attempt_observations (
    id text NOT NULL,
    model_turn_id text NOT NULL,
    run_id text NOT NULL,
    interaction_id text NOT NULL,
    target_id text NOT NULL,
    provider_id text NOT NULL,
    provider_name text NOT NULL,
    upstream_model text NOT NULL,
    protocol text NOT NULL,
    status text NOT NULL,
    status_code bigint,
    error_code text,
    started_at bigint NOT NULL,
    finished_at bigint,
    duration_ms bigint,
    first_token_ms bigint,
    input_tokens bigint,
    output_tokens bigint,
    cache_read_tokens bigint,
    cache_write_tokens bigint,
    reasoning_tokens bigint,
    usage_recorded boolean DEFAULT false NOT NULL,
    last_event_sequence bigint NOT NULL
);


--
-- Name: turn_chain_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.turn_chain_nodes (
    id text NOT NULL,
    kind text NOT NULL,
    parent_id text,
    principal text NOT NULL,
    payload_version bigint NOT NULL,
    payload text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    prefix_namespace text,
    prefix_fingerprint text,
    prefix_item_count bigint,
    prefix_completed_at bigint,
    CONSTRAINT turn_chain_nodes_kind_check CHECK ((kind = ANY (ARRAY['response'::text, 'agent'::text, 'web_search'::text]))),
    CONSTRAINT turn_chain_nodes_payload_version_check CHECK ((payload_version > 0))
);


--
-- Name: web_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.web_providers (
    id text NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    api_key text,
    last_test_success boolean,
    last_test_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    use_proxy boolean DEFAULT false NOT NULL,
    local_engines jsonb,
    CONSTRAINT web_providers_credentials_check CHECK ((((kind = 'local'::text) AND (api_key IS NULL) AND (local_engines IS NOT NULL)) OR ((kind = ANY (ARRAY['exa'::text, 'zhipu'::text])) AND (api_key IS NOT NULL) AND (length(TRIM(BOTH FROM api_key)) > 0) AND (local_engines IS NULL)))),
    CONSTRAINT web_providers_kind_check CHECK ((kind = ANY (ARRAY['local'::text, 'exa'::text, 'zhipu'::text])))
);


--
-- Name: admin_identity admin_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_identity
    ADD CONSTRAINT admin_identity_pkey PRIMARY KEY (singleton_id);


--
-- Name: admin_identity admin_identity_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_identity
    ADD CONSTRAINT admin_identity_username_key UNIQUE (username);


--
-- Name: admin_sessions admin_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_sessions
    ADD CONSTRAINT admin_sessions_pkey PRIMARY KEY (id);


--
-- Name: admin_sessions admin_sessions_refresh_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_sessions
    ADD CONSTRAINT admin_sessions_refresh_hash_key UNIQUE (refresh_hash);


--
-- Name: agent_definition_configs agent_definition_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_definition_configs
    ADD CONSTRAINT agent_definition_configs_pkey PRIMARY KEY (definition_id);


--
-- Name: agent_definition_revisions agent_definition_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_definition_revisions
    ADD CONSTRAINT agent_definition_revisions_pkey PRIMARY KEY (definition_id, version);


--
-- Name: agent_definition_revisions agent_definition_revisions_slug_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_definition_revisions
    ADD CONSTRAINT agent_definition_revisions_slug_version_key UNIQUE (slug, version);


--
-- Name: api_key_models api_key_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_models_pkey PRIMARY KEY (api_key_id, model_id);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_token_key UNIQUE (token);


--
-- Name: artifact_download_grants artifact_download_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_download_grants
    ADD CONSTRAINT artifact_download_grants_pkey PRIMARY KEY (token_hash);


--
-- Name: artifact_upload_parts artifact_upload_parts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_upload_parts
    ADD CONSTRAINT artifact_upload_parts_pkey PRIMARY KEY (upload_id, part_number);


--
-- Name: artifact_uploads artifact_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_uploads
    ADD CONSTRAINT artifact_uploads_pkey PRIMARY KEY (id);


--
-- Name: artifacts artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (id);


--
-- Name: debug_trace_manifests debug_trace_manifests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debug_trace_manifests
    ADD CONSTRAINT debug_trace_manifests_pkey PRIMARY KEY (trace_id);


--
-- Name: debug_trace_manifests debug_trace_manifests_relative_directory_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debug_trace_manifests
    ADD CONSTRAINT debug_trace_manifests_relative_directory_key UNIQUE (relative_directory);


--
-- Name: history_markers history_markers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_markers
    ADD CONSTRAINT history_markers_pkey PRIMARY KEY (reference);


--
-- Name: inference_run_observations inference_run_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inference_run_observations
    ADD CONSTRAINT inference_run_observations_pkey PRIMARY KEY (id);


--
-- Name: interaction_observations interaction_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interaction_observations
    ADD CONSTRAINT interaction_observations_pkey PRIMARY KEY (id);


--
-- Name: media_derivatives media_derivatives_derivative_artifact_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_derivatives
    ADD CONSTRAINT media_derivatives_derivative_artifact_id_key UNIQUE (derivative_artifact_id);


--
-- Name: media_derivatives media_derivatives_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_derivatives
    ADD CONSTRAINT media_derivatives_pkey PRIMARY KEY (source_artifact_id);


--
-- Name: model_backends model_backends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT model_backends_pkey PRIMARY KEY (id);


--
-- Name: model_turn_observations model_turn_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_turn_observations
    ADD CONSTRAINT model_turn_observations_pkey PRIMARY KEY (id);


--
-- Name: models models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- Name: native_compaction_sources native_compaction_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compaction_sources
    ADD CONSTRAINT native_compaction_sources_pkey PRIMARY KEY (record_id, source_id);


--
-- Name: native_compaction_states native_compaction_states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compaction_states
    ADD CONSTRAINT native_compaction_states_pkey PRIMARY KEY (record_id, fingerprint);


--
-- Name: native_compactions native_compactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compactions
    ADD CONSTRAINT native_compactions_pkey PRIMARY KEY (id);


--
-- Name: observation_events observation_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observation_events
    ADD CONSTRAINT observation_events_pkey PRIMARY KEY (sequence);


--
-- Name: provider_allowance_samples provider_allowance_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_allowance_samples
    ADD CONSTRAINT provider_allowance_samples_pkey PRIMARY KEY (id);


--
-- Name: provider_model_cost_rules provider_model_cost_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_model_cost_rules
    ADD CONSTRAINT provider_model_cost_rules_pkey PRIMARY KEY (provider_id, model_id, rule_index);


--
-- Name: provider_models provider_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_models
    ADD CONSTRAINT provider_models_pkey PRIMARY KEY (provider_id, model_id);


--
-- Name: provider_oauth_credentials provider_oauth_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_oauth_credentials
    ADD CONSTRAINT provider_oauth_credentials_pkey PRIMARY KEY (provider_id);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: rejected_request_observations rejected_request_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rejected_request_observations
    ADD CONSTRAINT rejected_request_observations_pkey PRIMARY KEY (id);


--
-- Name: reversible_redaction_mappings reversible_redaction_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reversible_redaction_mappings
    ADD CONSTRAINT reversible_redaction_mappings_pkey PRIMARY KEY (reference);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (name);


--
-- Name: target_attempt_observations target_attempt_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_attempt_observations
    ADD CONSTRAINT target_attempt_observations_pkey PRIMARY KEY (id);


--
-- Name: turn_chain_nodes turn_chain_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turn_chain_nodes
    ADD CONSTRAINT turn_chain_nodes_pkey PRIMARY KEY (id);


--
-- Name: web_providers web_providers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_providers
    ADD CONSTRAINT web_providers_name_key UNIQUE (name);


--
-- Name: web_providers web_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_providers
    ADD CONSTRAINT web_providers_pkey PRIMARY KEY (id);


--
-- Name: debug_manifests_expiry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX debug_manifests_expiry_idx ON public.debug_trace_manifests USING btree (tombstoned, expires_at);


--
-- Name: idx_admin_sessions_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_sessions_expiry ON public.admin_sessions USING btree (expires_at);


--
-- Name: idx_agent_definition_revisions_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_definition_revisions_slug ON public.agent_definition_revisions USING btree (slug, version);


--
-- Name: idx_api_key_models_model_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_key_models_model_id ON public.api_key_models USING btree (model_id);


--
-- Name: idx_api_keys_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_token ON public.api_keys USING btree (token);


--
-- Name: idx_artifact_download_grants_hold; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifact_download_grants_hold ON public.artifact_download_grants USING btree (artifact_id, expires_at);


--
-- Name: idx_artifact_uploads_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifact_uploads_expiry ON public.artifact_uploads USING btree (expires_at);


--
-- Name: idx_artifacts_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifacts_expiry ON public.artifacts USING btree (expires_at);


--
-- Name: idx_history_markers_execution; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_markers_execution ON public.history_markers USING btree (execution_state, lease_expires_at, execution_deadline);


--
-- Name: idx_history_markers_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_markers_expiry ON public.history_markers USING btree (expires_at);


--
-- Name: idx_history_markers_principal_reference; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_markers_principal_reference ON public.history_markers USING btree (principal, reference);


--
-- Name: idx_model_backends_model_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_backends_model_id ON public.model_backends USING btree (model_id);


--
-- Name: idx_models_route_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_models_route_id ON public.models USING btree (model_id);


--
-- Name: idx_native_compaction_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_native_compaction_source ON public.native_compaction_sources USING btree (source_id);


--
-- Name: idx_native_compaction_state_fingerprint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_native_compaction_state_fingerprint ON public.native_compaction_states USING btree (principal, fingerprint);


--
-- Name: idx_native_compaction_state_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_native_compaction_state_identity ON public.native_compaction_states USING btree (principal, native_identity);


--
-- Name: idx_native_compactions_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_native_compactions_expiry ON public.native_compactions USING btree (expires_at);


--
-- Name: idx_oauth_creds_connection_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_oauth_creds_connection_id ON public.provider_oauth_credentials USING btree (connection_id);


--
-- Name: idx_oauth_creds_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oauth_creds_expires ON public.provider_oauth_credentials USING btree (expires_at);


--
-- Name: idx_oauth_creds_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oauth_creds_status ON public.provider_oauth_credentials USING btree (status);


--
-- Name: idx_observation_events_client_tool_call; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_observation_events_client_tool_call ON public.observation_events USING btree (run_id, ((payload ->> 'tool_id'::text)), sequence DESC) WHERE (kind = ANY (ARRAY['client_tool_handoff'::text, 'client_tool_result'::text]));


--
-- Name: idx_observation_events_context; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_observation_events_context ON public.observation_events USING btree (interaction_id, sequence) WHERE (kind = ANY (ARRAY['compaction_operation'::text, 'native_compaction_associated'::text, 'retained_tail_associated'::text]));


--
-- Name: idx_provider_allowance_samples_item_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_allowance_samples_item_time ON public.provider_allowance_samples USING btree (provider_id, allowance_key, sampled_at);


--
-- Name: idx_provider_allowance_samples_sampled_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_allowance_samples_sampled_at ON public.provider_allowance_samples USING btree (sampled_at);


--
-- Name: idx_provider_model_cost_rules_threshold; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_provider_model_cost_rules_threshold ON public.provider_model_cost_rules USING btree (provider_id, model_id, rule_kind, threshold_tokens);


--
-- Name: idx_provider_models_provider_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_models_provider_name ON public.provider_models USING btree (provider_id, name);


--
-- Name: idx_provider_models_provider_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_models_provider_state ON public.provider_models USING btree (provider_id, presence, lifecycle_status, selection_policy);


--
-- Name: idx_reversible_redaction_mappings_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reversible_redaction_mappings_expiry ON public.reversible_redaction_mappings USING btree (expires_at);


--
-- Name: idx_reversible_redaction_mappings_principal_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reversible_redaction_mappings_principal_expiry ON public.reversible_redaction_mappings USING btree (principal, expires_at);


--
-- Name: idx_turn_chain_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_turn_chain_expiry ON public.turn_chain_nodes USING btree (expires_at);


--
-- Name: idx_turn_chain_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_turn_chain_parent ON public.turn_chain_nodes USING btree (parent_id);


--
-- Name: idx_turn_chain_principal_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_turn_chain_principal_kind ON public.turn_chain_nodes USING btree (principal, kind);


--
-- Name: idx_turn_chain_reusable_prefix; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_turn_chain_reusable_prefix ON public.turn_chain_nodes USING btree (principal, kind, prefix_namespace, prefix_fingerprint, prefix_item_count DESC, prefix_completed_at DESC, expires_at, id DESC) WHERE (prefix_namespace IS NOT NULL);


--
-- Name: idx_web_providers_local_singleton; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_web_providers_local_singleton ON public.web_providers USING btree (kind) WHERE (kind = 'local'::text);


--
-- Name: inference_runs_generation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inference_runs_generation_idx ON public.inference_run_observations USING btree (generation_node_id, generation_parent_id);


--
-- Name: inference_runs_interaction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inference_runs_interaction_idx ON public.inference_run_observations USING btree (interaction_id, started_at, id);


--
-- Name: inference_runs_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inference_runs_status_idx ON public.inference_run_observations USING btree (status, last_active_at);


--
-- Name: interaction_observations_expiry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interaction_observations_expiry_idx ON public.interaction_observations USING btree (expires_at);


--
-- Name: interaction_observations_filter_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interaction_observations_filter_idx ON public.interaction_observations USING btree (status, api_key_name, last_active_at DESC);


--
-- Name: interaction_observations_generation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interaction_observations_generation_idx ON public.interaction_observations USING btree (generation_root_id, last_active_at);


--
-- Name: interaction_observations_window_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interaction_observations_window_idx ON public.interaction_observations USING btree (root_id, last_active_at DESC, id);


--
-- Name: model_turns_analytics_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_turns_analytics_idx ON public.model_turn_observations USING btree (started_at, route_id, api_key_id, status);


--
-- Name: model_turns_interaction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_turns_interaction_idx ON public.model_turn_observations USING btree (interaction_id, started_at, id);


--
-- Name: observation_events_expiry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observation_events_expiry_idx ON public.observation_events USING btree (expires_at, sequence);


--
-- Name: observation_events_interaction_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observation_events_interaction_idx ON public.observation_events USING btree (interaction_id, sequence);


--
-- Name: observation_events_rejection_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observation_events_rejection_idx ON public.observation_events USING btree (rejection_id, sequence);


--
-- Name: observation_events_run_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX observation_events_run_idx ON public.observation_events USING btree (run_id, sequence);


--
-- Name: rejected_requests_expiry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rejected_requests_expiry_idx ON public.rejected_request_observations USING btree (expires_at);


--
-- Name: rejected_requests_window_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rejected_requests_window_idx ON public.rejected_request_observations USING btree (occurred_at DESC, id);


--
-- Name: target_attempts_analytics_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX target_attempts_analytics_idx ON public.target_attempt_observations USING btree (started_at, provider_id, upstream_model, target_id, status);


--
-- Name: target_attempts_turn_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX target_attempts_turn_idx ON public.target_attempt_observations USING btree (model_turn_id, started_at, id);


--
-- Name: admin_sessions admin_sessions_identity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_sessions
    ADD CONSTRAINT admin_sessions_identity_id_fkey FOREIGN KEY (identity_id) REFERENCES public.admin_identity(singleton_id) ON DELETE CASCADE;


--
-- Name: agent_definition_configs agent_definition_configs_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_definition_configs
    ADD CONSTRAINT agent_definition_configs_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE SET NULL;


--
-- Name: api_key_models api_key_models_api_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_models_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id) ON DELETE CASCADE;


--
-- Name: api_key_models api_key_models_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_key_models
    ADD CONSTRAINT api_key_models_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- Name: artifact_download_grants artifact_download_grants_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_download_grants
    ADD CONSTRAINT artifact_download_grants_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id) ON DELETE CASCADE;


--
-- Name: artifact_upload_parts artifact_upload_parts_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_upload_parts
    ADD CONSTRAINT artifact_upload_parts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.artifact_uploads(id) ON DELETE CASCADE;


--
-- Name: artifact_uploads artifact_uploads_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifact_uploads
    ADD CONSTRAINT artifact_uploads_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id) ON DELETE CASCADE;


--
-- Name: debug_trace_manifests debug_trace_manifests_rejection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debug_trace_manifests
    ADD CONSTRAINT debug_trace_manifests_rejection_id_fkey FOREIGN KEY (rejection_id) REFERENCES public.rejected_request_observations(id) ON DELETE CASCADE;


--
-- Name: debug_trace_manifests debug_trace_manifests_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debug_trace_manifests
    ADD CONSTRAINT debug_trace_manifests_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.inference_run_observations(id) ON DELETE CASCADE;


--
-- Name: inference_run_observations inference_run_observations_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inference_run_observations
    ADD CONSTRAINT inference_run_observations_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES public.interaction_observations(id) ON DELETE CASCADE;


--
-- Name: inference_run_observations inference_run_observations_parent_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inference_run_observations
    ADD CONSTRAINT inference_run_observations_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES public.inference_run_observations(id) ON DELETE SET NULL;


--
-- Name: interaction_observations interaction_observations_parent_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interaction_observations
    ADD CONSTRAINT interaction_observations_parent_interaction_id_fkey FOREIGN KEY (parent_interaction_id) REFERENCES public.interaction_observations(id) ON DELETE SET NULL;


--
-- Name: media_derivatives media_derivatives_derivative_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_derivatives
    ADD CONSTRAINT media_derivatives_derivative_artifact_id_fkey FOREIGN KEY (derivative_artifact_id) REFERENCES public.artifacts(id) ON DELETE CASCADE;


--
-- Name: media_derivatives media_derivatives_source_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.media_derivatives
    ADD CONSTRAINT media_derivatives_source_artifact_id_fkey FOREIGN KEY (source_artifact_id) REFERENCES public.artifacts(id) ON DELETE CASCADE;


--
-- Name: model_backends model_backends_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT model_backends_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- Name: model_backends model_backends_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_backends
    ADD CONSTRAINT model_backends_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: model_turn_observations model_turn_observations_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_turn_observations
    ADD CONSTRAINT model_turn_observations_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES public.interaction_observations(id) ON DELETE CASCADE;


--
-- Name: model_turn_observations model_turn_observations_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_turn_observations
    ADD CONSTRAINT model_turn_observations_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.inference_run_observations(id) ON DELETE CASCADE;


--
-- Name: native_compaction_sources native_compaction_sources_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compaction_sources
    ADD CONSTRAINT native_compaction_sources_record_id_fkey FOREIGN KEY (record_id) REFERENCES public.native_compactions(id) ON DELETE CASCADE;


--
-- Name: native_compaction_sources native_compaction_sources_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compaction_sources
    ADD CONSTRAINT native_compaction_sources_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.native_compactions(id) ON DELETE RESTRICT;


--
-- Name: native_compaction_states native_compaction_states_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compaction_states
    ADD CONSTRAINT native_compaction_states_record_id_fkey FOREIGN KEY (record_id) REFERENCES public.native_compactions(id) ON DELETE CASCADE;


--
-- Name: native_compactions native_compactions_source_generation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.native_compactions
    ADD CONSTRAINT native_compactions_source_generation_id_fkey FOREIGN KEY (source_generation_id) REFERENCES public.turn_chain_nodes(id) ON DELETE RESTRICT;


--
-- Name: observation_events observation_events_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observation_events
    ADD CONSTRAINT observation_events_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES public.interaction_observations(id) ON DELETE CASCADE;


--
-- Name: observation_events observation_events_rejection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observation_events
    ADD CONSTRAINT observation_events_rejection_id_fkey FOREIGN KEY (rejection_id) REFERENCES public.rejected_request_observations(id) ON DELETE CASCADE;


--
-- Name: observation_events observation_events_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.observation_events
    ADD CONSTRAINT observation_events_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.inference_run_observations(id) ON DELETE CASCADE;


--
-- Name: provider_allowance_samples provider_allowance_samples_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_allowance_samples
    ADD CONSTRAINT provider_allowance_samples_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: provider_model_cost_rules provider_model_cost_rules_provider_id_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_model_cost_rules
    ADD CONSTRAINT provider_model_cost_rules_provider_id_model_id_fkey FOREIGN KEY (provider_id, model_id) REFERENCES public.provider_models(provider_id, model_id) ON DELETE CASCADE;


--
-- Name: provider_models provider_models_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_models
    ADD CONSTRAINT provider_models_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: provider_oauth_credentials provider_oauth_credentials_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_oauth_credentials
    ADD CONSTRAINT provider_oauth_credentials_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE CASCADE;


--
-- Name: target_attempt_observations target_attempt_observations_interaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_attempt_observations
    ADD CONSTRAINT target_attempt_observations_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES public.interaction_observations(id) ON DELETE CASCADE;


--
-- Name: target_attempt_observations target_attempt_observations_model_turn_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_attempt_observations
    ADD CONSTRAINT target_attempt_observations_model_turn_id_fkey FOREIGN KEY (model_turn_id) REFERENCES public.model_turn_observations(id) ON DELETE CASCADE;


--
-- Name: target_attempt_observations target_attempt_observations_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.target_attempt_observations
    ADD CONSTRAINT target_attempt_observations_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.inference_run_observations(id) ON DELETE CASCADE;


--
-- Name: turn_chain_nodes turn_chain_nodes_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turn_chain_nodes
    ADD CONSTRAINT turn_chain_nodes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.turn_chain_nodes(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--


