import { Marked, Renderer, type Tokens } from 'marked'
import DOMPurify from 'dompurify'

const MARKED_OPTIONS = { async: false, gfm: true, breaks: true } as const

const HTML_ESCAPE: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }

export const MARKDOWN_SANITIZE = {
  ALLOWED_TAGS: [
    'p',
    'br',
    'strong',
    'em',
    'del',
    'code',
    'pre',
    'blockquote',
    'ul',
    'ol',
    'li',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    'span',
  ],
  // This one internal marker is generated by the renderer, never by raw HTML.
  ALLOWED_ATTR: ['start', 'data-markdown-fragment'],
  ALLOW_DATA_ATTR: false,
  ALLOW_ARIA_ATTR: false,
}

export interface MarkdownBlock {
  id: number
  html: string
  fragments: MarkdownFragment[]
}

export interface MarkdownFragment {
  id: number
  kind: 'math' | 'mermaid'
  source: string
  raw: string
  display: boolean
  complete: boolean
}

function escapedAt(source: string, position: number): boolean {
  let slashes = 0
  while (position > 0 && source[--position] === '\\') slashes++
  return slashes % 2 === 1
}

function mathToken(source: string): Tokens.Generic | undefined {
  const open = ['$$', '\\[', '\\(', '$'].find((delimiter) => source.startsWith(delimiter))
  if (!open) return
  const close = open === '\\[' ? '\\]' : open === '\\(' ? '\\)' : open
  const display = open === '$$' || open === '\\['
  let end = source.indexOf(close, open.length)
  while (end >= 0 && (escapedAt(source, end) || (open === '$' && source[end + 1] === '$'))) {
    end = source.indexOf(close, end + close.length)
  }
  const complete = end >= 0
  const raw = complete ? source.slice(0, end + close.length) : source
  return {
    type: 'math',
    raw,
    text: complete ? source.slice(open.length, end) : source.slice(open.length),
    display,
    complete,
  }
}

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (ch) => HTML_ESCAPE[ch] ?? ch)
}

// 原始 HTML 不能当 HTML 插入：`<title>` / `<textarea>` 会被浏览器抽走或隐藏，对话里只剩空气泡。
class ObservationRenderer extends Renderer {
  constructor(
    readonly minimumHeadingLevel: 1 | 2,
    readonly fragments: MarkdownFragment[],
  ) {
    super()
  }

  html({ text, block }: { text: string; block?: boolean }): string {
    const visible = text.replace(/<!--[\s\S]*?(?:-->|$)/g, '')
    if (!visible.trim()) return ''
    const escaped = escapeHtml(visible)
    return block ? `<p>${escaped}</p>` : escaped
  }

  fragment(fragment: Omit<MarkdownFragment, 'id'>): string {
    const id = this.fragments.length
    this.fragments.push({ id, ...fragment })
    if (fragment.kind === 'mermaid') {
      return `<pre data-markdown-fragment="${id}"><code>${escapeHtml(fragment.raw)}</code></pre>`
    }
    return `<span data-markdown-fragment="${id}"><code>${escapeHtml(fragment.raw)}</code></span>`
  }

  code(token: Tokens.Code): string {
    if (token.lang?.trim() !== 'mermaid' || token.codeBlockStyle === 'indented') return super.code(token)
    const opening = /^ {0,3}(`{3,}|~{3,})[^\n]*\n/.exec(token.raw)
    const fence = opening?.[1]
    const closing = fence
      ? new RegExp(`\\n {0,3}${fence[0] === '`' ? '`' : '~'}{${fence.length},}[ \\t]*(?:\\n)?$`)
      : null
    return this.fragment({
      kind: 'mermaid',
      source: token.text,
      raw: token.raw,
      display: true,
      complete: closing?.test(token.raw) ?? false,
    })
  }

  heading({ tokens, depth }: Tokens.Heading): string {
    const level = Math.max(depth, this.minimumHeadingLevel)
    return `<h${level}>${this.parser.parseInline(tokens)}</h${level}>\n`
  }
}

export function markdownBlocks(text: string, minimumHeadingLevel: 1 | 2 = 1): MarkdownBlock[] {
  const fragments: MarkdownFragment[] = []
  const renderer = new ObservationRenderer(minimumHeadingLevel, fragments)
  const markdown = new Marked({
    ...MARKED_OPTIONS,
    extensions: [
      {
        name: 'math',
        level: 'inline',
        start(source) {
          const index = source.search(/\$|\\(?:\(|\[)/)
          return index < 0 ? undefined : index
        },
        tokenizer: mathToken,
        renderer(token) {
          return renderer.fragment({
            kind: 'math',
            source: token.text as string,
            raw: token.raw,
            display: token.display as boolean,
            complete: token.complete as boolean,
          })
        },
      },
    ],
  })
  markdown.setOptions({ renderer })
  let offset = 0
  return markdown.lexer(text).map((token) => {
    const id = offset
    offset += token.raw.length
    const firstFragment = fragments.length
    return { id, html: markdown.parser([token]), fragments: fragments.slice(firstFragment) }
  })
}

// Keep heavy browser renderers out of the ordinary Markdown bundle.
let mermaidLibrary: Promise<(typeof import('mermaid'))['default']> | undefined
let katexLibrary: Promise<typeof import('katex')> | undefined
let katexStyles: Promise<unknown> | undefined

const MERMAID_UNSUPPORTED = [
  /<\s*\/?\s*[a-z!]|&(?:#\d+|#x[\da-f]+|\w+);/i, // HTML and entity-encoded HTML
  // eslint-disable-next-line no-control-regex -- Reject control characters before Mermaid parses untrusted source.
  /[\u0000-\u0008\u000b\u000c\u000e-\u001f]|\\(?![nt])/i, // controls and CSS escapes
  /%%\s*\{|^\s*---/, // directives and frontmatter configuration
  /(?:^|[\n;])\s*(?:click|style|classDef|linkStyle|UpdateElementStyle|UpdateRelStyle|UpdateBoundaryStyle)\b/i,
  /\b(?:img|image|icon|sprite)\s*[:=(]|@\{|::icon/i,
  /(?:https?|ftp|data|javascript|vbscript|file):|\/\/|url\s*\(|@import/i,
]

function assertSafeFragment(fragment: MarkdownFragment): void {
  if (!fragment.complete) throw new Error('Incomplete Markdown fragment')
  if (fragment.kind === 'mermaid') {
    // Reject before Mermaid touches its temporary DOM. Configuration, CSS, HTML,
    // images, icons and click handlers are not part of this read-only surface.
    if (MERMAID_UNSUPPORTED.some((pattern) => pattern.test(fragment.source))) {
      throw new Error('Unsupported diagram content')
    }
  } else if (
    /\\(?:href|url|includegraphics|html\w*|def|gdef|edef|xdef|let|futurelet|newcommand|renewcommand|providecommand|global|catcode|csname)\b/i.test(
      fragment.source,
    )
  ) {
    // No user-defined command aliases, persistent macros or trusted HTML/URL commands.
    throw new Error('Unsupported formula content')
  }
}

function safeCss(css: string): boolean {
  return !/@(?:import|font-face|namespace)|expression\s*\(|(?:https?|data|javascript|file):|\\|url\s*\(\s*(?!#[\w-]+\s*\))/i.test(
    css,
  )
}

/** Browser-only: returns sanitized, read-only output or rejects; callers retain source on failure. */
export async function renderMarkdownFragment(fragment: MarkdownFragment): Promise<string> {
  assertSafeFragment(fragment)
  if (fragment.kind === 'math') {
    katexLibrary ??= import('katex')
    const katex = await katexLibrary
    const html = katex.renderToString(fragment.source, {
      displayMode: fragment.display,
      throwOnError: true,
      trust: false,
      strict: 'error',
      macros: {},
      globalGroup: false,
      maxExpand: 1000,
      maxSize: 100,
      output: 'htmlAndMathml',
    })
    katexStyles ??= import('katex/dist/katex.min.css')
    await katexStyles
    return DOMPurify.sanitize(html, {
      USE_PROFILES: { html: true, mathMl: true },
      // KaTeX uses controlled SVG paths/lines for radicals and stretchy glyphs.
      ADD_TAGS: ['svg', 'path', 'line'],
      ADD_ATTR: ['viewBox', 'preserveAspectRatio', 'd', 'x1', 'x2', 'y1', 'y2', 'stroke', 'stroke-width', 'fill'],
      FORBID_TAGS: ['a', 'img', 'iframe', 'object', 'embed', 'script', 'style', 'link', 'video', 'audio', 'source'],
      FORBID_ATTR: ['href', 'src', 'srcset', 'xlink:href'],
      ALLOW_DATA_ATTR: false,
    })
  }

  mermaidLibrary ??= import('mermaid').then(({ default: mermaid }) => {
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: 'strict',
      htmlLabels: false,
      suppressErrorRendering: true,
      theme: 'base',
      fontFamily: 'inherit',
    })
    return mermaid
  })
  const mermaid = await mermaidLibrary
  const id = `markdown-diagram-${crypto.randomUUID()}`
  const temporary = document.createElement('div')
  temporary.setAttribute('aria-hidden', 'true')
  temporary.style.cssText = 'position:fixed;left:-100000px;top:0;visibility:hidden'
  document.body.append(temporary)
  try {
    const { svg } = await mermaid.render(id, fragment.source, temporary)
    const sanitized = DOMPurify.sanitize(svg, {
      USE_PROFILES: { svg: true },
      FORBID_TAGS: ['a', 'image', 'foreignObject', 'script', 'animate', 'animateMotion', 'animateTransform', 'set'],
      ALLOW_DATA_ATTR: false,
      ALLOW_ARIA_ATTR: true,
    })
    const documentSvg = new DOMParser().parseFromString(sanitized, 'image/svg+xml')
    if (documentSvg.querySelector('parsererror')) throw new Error('Invalid diagram output')
    for (const element of documentSvg.querySelectorAll('*')) {
      for (const attribute of [...element.attributes]) {
        const name = attribute.name.toLowerCase()
        if (
          name.startsWith('on') ||
          ((name === 'href' || name === 'xlink:href') && !/^#[\w-]+$/.test(attribute.value)) ||
          (name === 'style' && !safeCss(attribute.value)) ||
          (/url\s*\(/i.test(attribute.value) && !safeCss(attribute.value))
        )
          element.removeAttribute(attribute.name)
      }
      if (element.localName === 'style' && !safeCss(element.textContent ?? '')) element.remove()
    }
    return new XMLSerializer().serializeToString(documentSvg.documentElement)
  } finally {
    temporary.remove()
    // Do not bind Mermaid's generated callbacks: diagrams are presentation only.
  }
}
